### ISSUE TITLE
Waiting for pioneerAvrAccessory to be ready

### ISSUE THREAD

**Issue by Tim2309** [kazcangi/homebridge-pioneer-avr#11]
Hi,
I installed the plugin today and I only got following message in debug mode:
[9/4/2019, 9:06:44 PM] [My Pioneer AVR] Waiting for pioneerAvrAccessory to be ready

Every second I get the same message since 10 minutes, any fix for this?
I tested the different port, it ended with an error message.

Ive got an VSX-LX303

**Comment by Tim2309** [comment]
I think I found the problem, the 303 is not compatible with the iControl AV5 App

**Comment by kazcangi** [comment]
Hi,
Thanks for your feedback. Unfortunately this must be not compatible
