### ISSUE TITLE
Pioneer VSX-831

### ISSUE THREAD

**Issue by mark125431** [kazcangi/homebridge-pioneer-avr#12]
Hey.

I just can’t seem to get your plugin to work on my pioneer receiver.

The iControlAV5 app works fine.

Any ideas please ?

**Comment by kazcangi** [comment]
Hey,

I was looking for the protocol used by VSX-831. It seems that this AVR use eISCP protocol used by Onkyo AVRs. It is not compatible with Homebridge-pioneer-avr.
You should try Onkyo plugin : homebridge-onkyo-avr for Pioneer VSX-831

Regards
